######################## default configuration ####################
baseURL = "http://www.data-integration.services/"
title = "Data Integration Service"
# google analytics
googleAnalytics = "UA-177207474-2" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true