# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Details"
url = "service"
weight = 2

[[main]]
name = "Pricing"
url = "pricing"
weight = 3

[[main]]
name = "FAQ"
url = "faq"
weight = 4


# footer menu left

[[footer_left]]
name = "Home"
url = "/"

[[footer_left]]
name = "About Us"
url = "about"

# footer menu middle

[[footer_middle]]
name = "Details"
url = "service"

[[footer_middle]]
name = "Pricing"
url = "pricing"

[[footer_middle]]
name = "FAQ"
url = "faq"

# footer menu right

[[footer_right]]
name = "Contact us"
url = "contact/expert"

[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"



