#################### default parameters ################################
logo = "logos/logo_etlbox_dis_text.svg"
logo_width = "160px"
# OpenGraph / Twitter Card metadata
description = "Data Integration Services - we connect any system with any data source or API."
author = "ETLBox Office"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "/other/thanks/" 
favicon="favicon.ico"

# Navigation buttons
[navigation_button]
enable = true
label = "Get Started"
link = "contact/poc"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/etlbox/"